---
- name: Setup test
  hosts: olsrv
  gather_facts: no
  user: ansible
  become: true

  vars_files:
    - vars/default.config.yml

#  pre_tasks:
#    - name: Include playbook configuration.
#      include_vars: "{{ item }}"
#      with_fileglob:
#        - "{{ playbook_dir }}/config.yml"
#      tags: ['always']

  tasks:
    - import_tasks: tasks/test.yml
      when: cfg_test
      tags: ['test']

    - import_tasks: tasks/group.yml
      #      when: cfg_test
      tags: ['group']

    - import_tasks: tasks/user.yml
      #      when: cfg_test
      tags: ['user']


#    - import_tasks: tasks/terminal.yml
#      when: configure_terminal
#      tags: ['terminal']

