---
- hosts: idrac
  gather_facts: False
  connection: local

  collections:
    - dellemc.openmanage

#  vars_files:
#    - vars/default.config.yml

#  pre_tasks:
#    - name: Include playbook configuration.
#      include_vars: "{{ item }}"
#      with_fileglob:
#        - "{{ playbook_dir }}/config.yml"
#      tags: ['always']

  tasks:
    - import_tasks: tasks/idrac_sys_inventory.yml
      tags:
        - never
        - inventory


