---
- hosts: idrac
  connection: local
  name: Get system inventory
  gather_facts: False

  collections:
    - dellemc.openmanage

  tasks:
  - name: Get system inventory.
    dellemc.openmanage.idrac_system_info:
      idrac_ip: "{{ idrac_ip }}"
      idrac_user: "{{ idrac_user }}"
      idrac_password: "{{ idrac_pass }}"
      validate_certs: False   # Optional
#      ca_path: "/tmp/ca_cert.pem"
    register: system_inventory

  - name: Write results to local output file
    copy:
      content: "{{ system_inventory }}"
      dest: "{{ output_inventory_json }}"
    delegate_to: localhost


# - hosts: localhost
#   gather_facts: false
#   tasks:
#     - name: Write results to local output file
#       copy:
#         dest: "./output/system_inventory_output.json"
#         content: |
#           {% for host in groups.idrac %}
#           === {{ host }} ==

#           {{hostvars[host].system_inventory}}

#           {% endfor %}

# https://stackoverflow.com/questions/65944076/ansible-save-output-from-multiple-hosts
#
#
